package generator

import "google.golang.org/protobuf/compiler/protogen"

// Generator drives emission of *_ws.pb.go files.
type Generator struct {
	Settings *PluginSettings
	Plugin   *protogen.Plugin
}

func NewGenerator(p *protogen.Plugin, settings *PluginSettings) (*Generator, error) {
	return &Generator{Settings: settings, Plugin: p}, nil
}

// Generate emits one <file>_ws.pb.go per proto file that declares services.
func (g *Generator) Generate() error {
	for _, file := range g.Plugin.Files {
		if !file.Generate || len(file.Services) == 0 {
			continue
		}
		gf := g.Plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+"_ws.pb.go", file.GoImportPath)
		gf.P("// Code generated by protoc-gen-go-ws. DO NOT EDIT.")
		gf.P("// source: ", file.Desc.Path())
		gf.P()
		gf.P("package ", string(file.GoPackageName))
		gf.P()
		for _, svc := range file.Services {
			g.genService(gf, svc)
			g.genClient(gf, svc)
			g.genGRPCBridge(gf, svc)
		}
	}
	return nil
}

func (g *Generator) genClient(gf *protogen.GeneratedFile, svc *protogen.Service)     {}
func (g *Generator) genGRPCBridge(gf *protogen.GeneratedFile, svc *protogen.Service) {}
