// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: transport/options.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathPrefix    string                 `protobuf:"bytes,1,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"` // route prefix override; default ""
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_transport_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_transport_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_transport_options_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceOptions) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

type MethodOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Route           string                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`                                               // route override; default "/pkg.Service/Method"
	MaxMessageBytes uint32                 `protobuf:"varint,2,opt,name=max_message_bytes,json=maxMessageBytes,proto3" json:"max_message_bytes,omitempty"` // 0 = unlimited
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_transport_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_transport_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_transport_options_proto_rawDescGZIP(), []int{1}
}

func (x *MethodOptions) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *MethodOptions) GetMaxMessageBytes() uint32 {
	if x != nil {
		return x.MaxMessageBytes
	}
	return 0
}

var file_transport_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         70123,
		Name:          "wsproto.transport.v1.service",
		Tag:           "bytes,70123,opt,name=service",
		Filename:      "transport/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         70123,
		Name:          "wsproto.transport.v1.method",
		Tag:           "bytes,70123,opt,name=method",
		Filename:      "transport/options.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional wsproto.transport.v1.ServiceOptions service = 70123;
	E_Service = &file_transport_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional wsproto.transport.v1.MethodOptions method = 70123;
	E_Method = &file_transport_options_proto_extTypes[1]
)

var File_transport_options_proto protoreflect.FileDescriptor

const file_transport_options_proto_rawDesc = "" +
	"\n" +
	"\x17transport/options.proto\x12\x14wsproto.transport.v1\x1a google/protobuf/descriptor.proto\"1\n" +
	"\x0eServiceOptions\x12\x1f\n" +
	"\vpath_prefix\x18\x01 \x01(\tR\n" +
	"pathPrefix\"Q\n" +
	"\rMethodOptions\x12\x14\n" +
	"\x05route\x18\x01 \x01(\tR\x05route\x12*\n" +
	"\x11max_message_bytes\x18\x02 \x01(\rR\x0fmaxMessageBytes:a\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\xeb\xa3\x04 \x01(\v2$.wsproto.transport.v1.ServiceOptionsR\aservice:]\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18\xeb\xa3\x04 \x01(\v2#.wsproto.transport.v1.MethodOptionsR\x06methodB2Z0github.com/gopherex/ws-proto/transport;transportb\x06proto3"

var (
	file_transport_options_proto_rawDescOnce sync.Once
	file_transport_options_proto_rawDescData []byte
)

func file_transport_options_proto_rawDescGZIP() []byte {
	file_transport_options_proto_rawDescOnce.Do(func() {
		file_transport_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_options_proto_rawDesc), len(file_transport_options_proto_rawDesc)))
	})
	return file_transport_options_proto_rawDescData
}

var file_transport_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transport_options_proto_goTypes = []any{
	(*ServiceOptions)(nil),              // 0: wsproto.transport.v1.ServiceOptions
	(*MethodOptions)(nil),               // 1: wsproto.transport.v1.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 2: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 3: google.protobuf.MethodOptions
}
var file_transport_options_proto_depIdxs = []int32{
	2, // 0: wsproto.transport.v1.service:extendee -> google.protobuf.ServiceOptions
	3, // 1: wsproto.transport.v1.method:extendee -> google.protobuf.MethodOptions
	0, // 2: wsproto.transport.v1.service:type_name -> wsproto.transport.v1.ServiceOptions
	1, // 3: wsproto.transport.v1.method:type_name -> wsproto.transport.v1.MethodOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_options_proto_init() }
func file_transport_options_proto_init() {
	if File_transport_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_options_proto_rawDesc), len(file_transport_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_transport_options_proto_goTypes,
		DependencyIndexes: file_transport_options_proto_depIdxs,
		MessageInfos:      file_transport_options_proto_msgTypes,
		ExtensionInfos:    file_transport_options_proto_extTypes,
	}.Build()
	File_transport_options_proto = out.File
	file_transport_options_proto_goTypes = nil
	file_transport_options_proto_depIdxs = nil
}
