// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: transport/transport.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_UNSPECIFIED   Kind = 0
	Kind_KIND_OPEN          Kind = 1
	Kind_KIND_MSG           Kind = 2
	Kind_KIND_HALF_CLOSE    Kind = 3
	Kind_KIND_END           Kind = 4
	Kind_KIND_RST           Kind = 5
	Kind_KIND_HEADER        Kind = 6 // server->client only: leading response metadata, at most once before any MSG
	Kind_KIND_WINDOW_UPDATE Kind = 7 // flow control: returns credit (window delta bytes) to the sender for stream_id
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_OPEN",
		2: "KIND_MSG",
		3: "KIND_HALF_CLOSE",
		4: "KIND_END",
		5: "KIND_RST",
		6: "KIND_HEADER",
		7: "KIND_WINDOW_UPDATE",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":   0,
		"KIND_OPEN":          1,
		"KIND_MSG":           2,
		"KIND_HALF_CLOSE":    3,
		"KIND_END":           4,
		"KIND_RST":           5,
		"KIND_HEADER":        6,
		"KIND_WINDOW_UPDATE": 7,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_transport_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_transport_transport_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_transport_transport_proto_rawDescGZIP(), []int{0}
}

// Frame is the single wire unit multiplexed over one WebSocket connection.
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"` // client-allocated, monotonic per connection
	Kind          Kind                   `protobuf:"varint,2,opt,name=kind,proto3,enum=wsproto.transport.v1.Kind" json:"kind,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // OPEN: metadata + deadline; END: trailers
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                                                           // MSG: one marshaled request/response message
	Status        *Status                `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                                                             // END only
	Method        string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`                                                                             // OPEN only: "/pkg.Service/Method"
	Window        uint32                 `protobuf:"varint,8,opt,name=window,proto3" json:"window,omitempty"`                                                                            // WINDOW_UPDATE only: credit delta in bytes returned to the sender for stream_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_transport_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_transport_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_transport_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Frame) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *Frame) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Frame) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Frame) GetWindow() uint32 {
	if x != nil {
		return x.Window
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // gRPC-style status code
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       [][]byte               `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"` // marshaled google.protobuf.Any payloads
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_transport_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_transport_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_transport_transport_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Status) GetDetails() [][]byte {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_transport_transport_proto protoreflect.FileDescriptor

const file_transport_transport_proto_rawDesc = "" +
	"\n" +
	"\x19transport/transport.proto\x12\x14wsproto.transport.v1\"\xd4\x02\n" +
	"\x05Frame\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x12.\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1a.wsproto.transport.v1.KindR\x04kind\x12B\n" +
	"\aheaders\x18\x03 \x03(\v2(.wsproto.transport.v1.Frame.HeadersEntryR\aheaders\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x124\n" +
	"\x06status\x18\x05 \x01(\v2\x1c.wsproto.transport.v1.StatusR\x06status\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x16\n" +
	"\x06window\x18\b \x01(\rR\x06window\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x03(\fR\adetails*\x93\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tKIND_OPEN\x10\x01\x12\f\n" +
	"\bKIND_MSG\x10\x02\x12\x13\n" +
	"\x0fKIND_HALF_CLOSE\x10\x03\x12\f\n" +
	"\bKIND_END\x10\x04\x12\f\n" +
	"\bKIND_RST\x10\x05\x12\x0f\n" +
	"\vKIND_HEADER\x10\x06\x12\x16\n" +
	"\x12KIND_WINDOW_UPDATE\x10\aB2Z0github.com/gopherex/ws-proto/transport;transportb\x06proto3"

var (
	file_transport_transport_proto_rawDescOnce sync.Once
	file_transport_transport_proto_rawDescData []byte
)

func file_transport_transport_proto_rawDescGZIP() []byte {
	file_transport_transport_proto_rawDescOnce.Do(func() {
		file_transport_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_transport_proto_rawDesc), len(file_transport_transport_proto_rawDesc)))
	})
	return file_transport_transport_proto_rawDescData
}

var file_transport_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transport_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_transport_transport_proto_goTypes = []any{
	(Kind)(0),      // 0: wsproto.transport.v1.Kind
	(*Frame)(nil),  // 1: wsproto.transport.v1.Frame
	(*Status)(nil), // 2: wsproto.transport.v1.Status
	nil,            // 3: wsproto.transport.v1.Frame.HeadersEntry
}
var file_transport_transport_proto_depIdxs = []int32{
	0, // 0: wsproto.transport.v1.Frame.kind:type_name -> wsproto.transport.v1.Kind
	3, // 1: wsproto.transport.v1.Frame.headers:type_name -> wsproto.transport.v1.Frame.HeadersEntry
	2, // 2: wsproto.transport.v1.Frame.status:type_name -> wsproto.transport.v1.Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_transport_transport_proto_init() }
func file_transport_transport_proto_init() {
	if File_transport_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_transport_proto_rawDesc), len(file_transport_transport_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_transport_proto_goTypes,
		DependencyIndexes: file_transport_transport_proto_depIdxs,
		EnumInfos:         file_transport_transport_proto_enumTypes,
		MessageInfos:      file_transport_transport_proto_msgTypes,
	}.Build()
	File_transport_transport_proto = out.File
	file_transport_transport_proto_goTypes = nil
	file_transport_transport_proto_depIdxs = nil
}
