// Code generated by protoc-gen-go-ws. DO NOT EDIT.
// source: proto/echo/v1/echo.proto

package echov1

import (
	context "context"
	wsrpc "github.com/gopherex/ws-proto/wsrpc"
	codes "google.golang.org/grpc/codes"
	metadata "google.golang.org/grpc/metadata"
	proto "google.golang.org/protobuf/proto"
	io "io"
)

// EchoServiceHandler is the server API for the EchoService service.
type EchoServiceHandler interface {
	Unary(ctx context.Context, req *UnaryRequest) (*UnaryResponse, error)
	ServerStream(ctx context.Context, req *ServerStreamRequest, stream *EchoService_ServerStreamServerWS) error
	ClientStream(ctx context.Context, stream *EchoService_ClientStreamServerWS) (*ClientStreamResponse, error)
	Bidi(ctx context.Context, stream *EchoService_BidiServerWS) error
}

// EchoService_ServerStreamServerWS is the typed server stream for EchoService.ServerStream.
type EchoService_ServerStreamServerWS struct {
	stream *wsrpc.Stream
}

func (x *EchoService_ServerStreamServerWS) Send(msg *ServerStreamResponse) error {
	return x.stream.Send(msg)
}

func (x *EchoService_ServerStreamServerWS) Recv() (*ServerStreamRequest, error) {
	msg := new(ServerStreamRequest)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *EchoService_ServerStreamServerWS) Context() context.Context {
	return x.stream.Context()
}

// EchoService_ClientStreamServerWS is the typed server stream for EchoService.ClientStream.
type EchoService_ClientStreamServerWS struct {
	stream *wsrpc.Stream
}

func (x *EchoService_ClientStreamServerWS) Send(msg *ClientStreamResponse) error {
	return x.stream.Send(msg)
}

func (x *EchoService_ClientStreamServerWS) Recv() (*ClientStreamRequest, error) {
	msg := new(ClientStreamRequest)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *EchoService_ClientStreamServerWS) Context() context.Context {
	return x.stream.Context()
}

// EchoService_BidiServerWS is the typed server stream for EchoService.Bidi.
type EchoService_BidiServerWS struct {
	stream *wsrpc.Stream
}

func (x *EchoService_BidiServerWS) Send(msg *BidiResponse) error {
	return x.stream.Send(msg)
}

func (x *EchoService_BidiServerWS) Recv() (*BidiRequest, error) {
	msg := new(BidiRequest)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *EchoService_BidiServerWS) Context() context.Context {
	return x.stream.Context()
}

// RegisterEchoServiceHandler registers impl on srv for all EchoService methods.
func RegisterEchoServiceHandler(srv *wsrpc.Server, impl EchoServiceHandler) {
	srv.Register("/echo.v1.EchoService/Unary", func(ctx context.Context, s *wsrpc.Stream) error {
		req := new(UnaryRequest)
		if err := s.Recv(req); err != nil && err != io.EOF {
			return err
		}
		res, err := impl.Unary(ctx, req)
		if err != nil {
			return err
		}
		return s.Send(res)
	})
	srv.Register("/echo.v1.EchoService/ServerStream", func(ctx context.Context, s *wsrpc.Stream) error {
		req := new(ServerStreamRequest)
		if err := s.Recv(req); err != nil && err != io.EOF {
			return err
		}
		return impl.ServerStream(ctx, req, &EchoService_ServerStreamServerWS{stream: s})
	})
	srv.Register("/echo.v1.EchoService/ClientStream", func(ctx context.Context, s *wsrpc.Stream) error {
		res, err := impl.ClientStream(ctx, &EchoService_ClientStreamServerWS{stream: s})
		if err != nil {
			return err
		}
		return s.Send(res)
	})
	srv.Register("/echo.v1.EchoService/Bidi", func(ctx context.Context, s *wsrpc.Stream) error {
		return impl.Bidi(ctx, &EchoService_BidiServerWS{stream: s})
	})
}

// EchoServiceWSClient is the client API for the EchoService service.
type EchoServiceWSClient interface {
	Unary(ctx context.Context, req *UnaryRequest) (*UnaryResponse, error)
	ServerStream(ctx context.Context, req *ServerStreamRequest) (*EchoService_ServerStreamClientWS, error)
	ClientStream(ctx context.Context) (*EchoService_ClientStreamClientWS, error)
	Bidi(ctx context.Context) (*EchoService_BidiClientWS, error)
}

type echoServiceWSClient struct {
	cc *wsrpc.ClientConn
}

// NewEchoServiceWSClient returns a EchoServiceWSClient backed by cc.
func NewEchoServiceWSClient(cc *wsrpc.ClientConn) EchoServiceWSClient {
	return &echoServiceWSClient{cc: cc}
}

// EchoService_ServerStreamClientWS is the typed client stream for EchoService.ServerStream.
type EchoService_ServerStreamClientWS struct {
	stream *wsrpc.Stream
}

func (x *EchoService_ServerStreamClientWS) Send(msg *ServerStreamRequest) error {
	return x.stream.Send(msg)
}

func (x *EchoService_ServerStreamClientWS) Recv() (*ServerStreamResponse, error) {
	msg := new(ServerStreamResponse)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *EchoService_ServerStreamClientWS) CloseSend() error {
	return x.stream.CloseSend()
}

// EchoService_ClientStreamClientWS is the typed client stream for EchoService.ClientStream.
type EchoService_ClientStreamClientWS struct {
	stream *wsrpc.Stream
}

func (x *EchoService_ClientStreamClientWS) Send(msg *ClientStreamRequest) error {
	return x.stream.Send(msg)
}

func (x *EchoService_ClientStreamClientWS) Recv() (*ClientStreamResponse, error) {
	msg := new(ClientStreamResponse)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *EchoService_ClientStreamClientWS) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *EchoService_ClientStreamClientWS) CloseAndRecv() (*ClientStreamResponse, error) {
	if err := x.stream.CloseSend(); err != nil {
		return nil, err
	}
	return x.Recv()
}

// EchoService_BidiClientWS is the typed client stream for EchoService.Bidi.
type EchoService_BidiClientWS struct {
	stream *wsrpc.Stream
}

func (x *EchoService_BidiClientWS) Send(msg *BidiRequest) error {
	return x.stream.Send(msg)
}

func (x *EchoService_BidiClientWS) Recv() (*BidiResponse, error) {
	msg := new(BidiResponse)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *EchoService_BidiClientWS) CloseSend() error {
	return x.stream.CloseSend()
}

func (c *echoServiceWSClient) Unary(ctx context.Context, req *UnaryRequest) (*UnaryResponse, error) {
	s, err := c.cc.NewStream(ctx, "/echo.v1.EchoService/Unary", nil)
	if err != nil {
		return nil, err
	}
	if err := s.Send(req); err != nil {
		return nil, err
	}
	if err := s.CloseSend(); err != nil {
		return nil, err
	}
	res := new(UnaryResponse)
	if err := s.Recv(res); err != nil {
		return nil, err
	}
	if err := s.Recv(new(UnaryResponse)); err != nil && err != io.EOF {
		return nil, err
	}
	return res, nil
}

func (c *echoServiceWSClient) ServerStream(ctx context.Context, req *ServerStreamRequest) (*EchoService_ServerStreamClientWS, error) {
	s, err := c.cc.NewStream(ctx, "/echo.v1.EchoService/ServerStream", nil)
	if err != nil {
		return nil, err
	}
	if err := s.Send(req); err != nil {
		return nil, err
	}
	if err := s.CloseSend(); err != nil {
		return nil, err
	}
	return &EchoService_ServerStreamClientWS{stream: s}, nil
}

func (c *echoServiceWSClient) ClientStream(ctx context.Context) (*EchoService_ClientStreamClientWS, error) {
	s, err := c.cc.NewStream(ctx, "/echo.v1.EchoService/ClientStream", nil)
	if err != nil {
		return nil, err
	}
	return &EchoService_ClientStreamClientWS{stream: s}, nil
}

func (c *echoServiceWSClient) Bidi(ctx context.Context) (*EchoService_BidiClientWS, error) {
	s, err := c.cc.NewStream(ctx, "/echo.v1.EchoService/Bidi", nil)
	if err != nil {
		return nil, err
	}
	return &EchoService_BidiClientWS{stream: s}, nil
}

// echoServiceGRPCBridge adapts a gRPC EchoServiceServer to a EchoServiceHandler.
type echoServiceGRPCBridge struct {
	impl EchoServiceServer
}

// EchoServiceFromGRPC wraps a protoc-gen-go-grpc server so it can be
// registered on a wsrpc.Server via RegisterEchoServiceHandler.
func EchoServiceFromGRPC(impl EchoServiceServer) EchoServiceHandler {
	return &echoServiceGRPCBridge{impl: impl}
}

func (b *echoServiceGRPCBridge) Unary(ctx context.Context, req *UnaryRequest) (*UnaryResponse, error) {
	return b.impl.Unary(ctx, req)
}

func (b *echoServiceGRPCBridge) ServerStream(ctx context.Context, req *ServerStreamRequest, stream *EchoService_ServerStreamServerWS) error {
	return b.impl.ServerStream(req, &echoServiceServerStreamGRPCShim{stream: stream.stream, ctx: ctx})
}

func (b *echoServiceGRPCBridge) ClientStream(ctx context.Context, stream *EchoService_ClientStreamServerWS) (*ClientStreamResponse, error) {
	sh := &echoServiceClientStreamGRPCShim{stream: stream.stream, ctx: ctx}
	if err := b.impl.ClientStream(sh); err != nil {
		return nil, err
	}
	if sh.resp == nil {
		return new(ClientStreamResponse), nil
	}
	return sh.resp, nil
}

func (b *echoServiceGRPCBridge) Bidi(ctx context.Context, stream *EchoService_BidiServerWS) error {
	return b.impl.Bidi(&echoServiceBidiGRPCShim{stream: stream.stream, ctx: ctx})
}

// echoServiceServerStreamGRPCShim adapts *wsrpc.Stream to the gRPC server stream for EchoService.ServerStream.
type echoServiceServerStreamGRPCShim struct {
	stream *wsrpc.Stream
	ctx    context.Context
}

func (x *echoServiceServerStreamGRPCShim) Send(msg *ServerStreamResponse) error {
	return x.stream.Send(msg)
}

func (x *echoServiceServerStreamGRPCShim) Recv() (*ServerStreamRequest, error) {
	msg := new(ServerStreamRequest)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *echoServiceServerStreamGRPCShim) Context() context.Context { return x.ctx }

func (x *echoServiceServerStreamGRPCShim) SetHeader(metadata.MD) error { return nil }

func (x *echoServiceServerStreamGRPCShim) SendHeader(metadata.MD) error { return nil }

func (x *echoServiceServerStreamGRPCShim) SetTrailer(metadata.MD) {}

func (x *echoServiceServerStreamGRPCShim) SendMsg(m any) error {
	pm, ok := m.(proto.Message)
	if !ok {
		return wsrpc.Errorf(codes.Unimplemented, "wsrpc: SendMsg expected proto.Message")
	}
	return x.stream.Send(pm)
}

func (x *echoServiceServerStreamGRPCShim) RecvMsg(m any) error {
	pm, ok := m.(proto.Message)
	if !ok {
		return wsrpc.Errorf(codes.Unimplemented, "wsrpc: RecvMsg expected proto.Message")
	}
	return x.stream.Recv(pm)
}

// echoServiceClientStreamGRPCShim adapts *wsrpc.Stream to the gRPC server stream for EchoService.ClientStream.
type echoServiceClientStreamGRPCShim struct {
	stream *wsrpc.Stream
	ctx    context.Context
	resp   *ClientStreamResponse // captured by SendAndClose
}

func (x *echoServiceClientStreamGRPCShim) Recv() (*ClientStreamRequest, error) {
	msg := new(ClientStreamRequest)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *echoServiceClientStreamGRPCShim) SendAndClose(msg *ClientStreamResponse) error {
	x.resp = msg
	return nil
}

func (x *echoServiceClientStreamGRPCShim) Context() context.Context { return x.ctx }

func (x *echoServiceClientStreamGRPCShim) SetHeader(metadata.MD) error { return nil }

func (x *echoServiceClientStreamGRPCShim) SendHeader(metadata.MD) error { return nil }

func (x *echoServiceClientStreamGRPCShim) SetTrailer(metadata.MD) {}

func (x *echoServiceClientStreamGRPCShim) SendMsg(m any) error {
	pm, ok := m.(proto.Message)
	if !ok {
		return wsrpc.Errorf(codes.Unimplemented, "wsrpc: SendMsg expected proto.Message")
	}
	return x.stream.Send(pm)
}

func (x *echoServiceClientStreamGRPCShim) RecvMsg(m any) error {
	pm, ok := m.(proto.Message)
	if !ok {
		return wsrpc.Errorf(codes.Unimplemented, "wsrpc: RecvMsg expected proto.Message")
	}
	return x.stream.Recv(pm)
}

// echoServiceBidiGRPCShim adapts *wsrpc.Stream to the gRPC server stream for EchoService.Bidi.
type echoServiceBidiGRPCShim struct {
	stream *wsrpc.Stream
	ctx    context.Context
}

func (x *echoServiceBidiGRPCShim) Send(msg *BidiResponse) error {
	return x.stream.Send(msg)
}

func (x *echoServiceBidiGRPCShim) Recv() (*BidiRequest, error) {
	msg := new(BidiRequest)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *echoServiceBidiGRPCShim) Context() context.Context { return x.ctx }

func (x *echoServiceBidiGRPCShim) SetHeader(metadata.MD) error { return nil }

func (x *echoServiceBidiGRPCShim) SendHeader(metadata.MD) error { return nil }

func (x *echoServiceBidiGRPCShim) SetTrailer(metadata.MD) {}

func (x *echoServiceBidiGRPCShim) SendMsg(m any) error {
	pm, ok := m.(proto.Message)
	if !ok {
		return wsrpc.Errorf(codes.Unimplemented, "wsrpc: SendMsg expected proto.Message")
	}
	return x.stream.Send(pm)
}

func (x *echoServiceBidiGRPCShim) RecvMsg(m any) error {
	pm, ok := m.(proto.Message)
	if !ok {
		return wsrpc.Errorf(codes.Unimplemented, "wsrpc: RecvMsg expected proto.Message")
	}
	return x.stream.Recv(pm)
}
