// Code generated by protoc-gen-go-ws. DO NOT EDIT.
// source: proto/echo/v1/echo.proto

package echov1

import (
	context "context"
	wsrpc "github.com/gopherex/ws-proto/wsrpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	metadata "google.golang.org/grpc/metadata"
	proto "google.golang.org/protobuf/proto"
	io "io"
)

// EchoServiceHandler is the server API for the EchoService service.
type EchoServiceHandler interface {
	Unary(ctx context.Context, req *UnaryRequest) (*UnaryResponse, error)
	ServerStream(ctx context.Context, req *ServerStreamRequest, stream *EchoService_ServerStreamServerWS) error
	ClientStream(ctx context.Context, stream *EchoService_ClientStreamServerWS) (*ClientStreamResponse, error)
	Bidi(ctx context.Context, stream *EchoService_BidiServerWS) error
}

// EchoService_ServerStreamServerWS is the typed server stream for EchoService.ServerStream.
type EchoService_ServerStreamServerWS struct {
	stream *wsrpc.Stream
}

func (x *EchoService_ServerStreamServerWS) Send(msg *ServerStreamResponse) error {
	return x.stream.Send(msg)
}

func (x *EchoService_ServerStreamServerWS) Recv() (*ServerStreamRequest, error) {
	msg := new(ServerStreamRequest)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *EchoService_ServerStreamServerWS) Context() context.Context {
	return x.stream.Context()
}

// EchoService_ClientStreamServerWS is the typed server stream for EchoService.ClientStream.
type EchoService_ClientStreamServerWS struct {
	stream *wsrpc.Stream
}

func (x *EchoService_ClientStreamServerWS) Send(msg *ClientStreamResponse) error {
	return x.stream.Send(msg)
}

func (x *EchoService_ClientStreamServerWS) Recv() (*ClientStreamRequest, error) {
	msg := new(ClientStreamRequest)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *EchoService_ClientStreamServerWS) Context() context.Context {
	return x.stream.Context()
}

// EchoService_BidiServerWS is the typed server stream for EchoService.Bidi.
type EchoService_BidiServerWS struct {
	stream *wsrpc.Stream
}

func (x *EchoService_BidiServerWS) Send(msg *BidiResponse) error {
	return x.stream.Send(msg)
}

func (x *EchoService_BidiServerWS) Recv() (*BidiRequest, error) {
	msg := new(BidiRequest)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *EchoService_BidiServerWS) Context() context.Context {
	return x.stream.Context()
}

// RegisterEchoServiceHandler registers impl on srv for all EchoService methods.
func RegisterEchoServiceHandler(srv *wsrpc.Server, impl EchoServiceHandler) {
	srv.Register("/echo.v1.EchoService/Unary", func(ctx context.Context, s *wsrpc.Stream) error {
		req := new(UnaryRequest)
		if err := s.Recv(req); err != nil && err != io.EOF {
			return err
		}
		res, err := impl.Unary(ctx, req)
		if err != nil {
			return err
		}
		return s.Send(res)
	})
	srv.Register("/echo.v1.EchoService/ServerStream", func(ctx context.Context, s *wsrpc.Stream) error {
		req := new(ServerStreamRequest)
		if err := s.Recv(req); err != nil && err != io.EOF {
			return err
		}
		return impl.ServerStream(ctx, req, &EchoService_ServerStreamServerWS{stream: s})
	})
	srv.Register("/echo.v1.EchoService/ClientStream", func(ctx context.Context, s *wsrpc.Stream) error {
		res, err := impl.ClientStream(ctx, &EchoService_ClientStreamServerWS{stream: s})
		if err != nil {
			return err
		}
		return s.Send(res)
	})
	srv.Register("/echo.v1.EchoService/Bidi", func(ctx context.Context, s *wsrpc.Stream) error {
		return impl.Bidi(ctx, &EchoService_BidiServerWS{stream: s})
	})
}

// EchoServiceWSClient is the client API for the EchoService service.
type EchoServiceWSClient interface {
	Unary(ctx context.Context, req *UnaryRequest, opts ...wsrpc.CallOption) (*UnaryResponse, error)
	ServerStream(ctx context.Context, req *ServerStreamRequest, opts ...wsrpc.CallOption) (*EchoService_ServerStreamClientWS, error)
	ClientStream(ctx context.Context, opts ...wsrpc.CallOption) (*EchoService_ClientStreamClientWS, error)
	Bidi(ctx context.Context, opts ...wsrpc.CallOption) (*EchoService_BidiClientWS, error)
}

type echoServiceWSClient struct {
	cc *wsrpc.ClientConn
}

// NewEchoServiceWSClient returns a EchoServiceWSClient backed by cc.
func NewEchoServiceWSClient(cc *wsrpc.ClientConn) EchoServiceWSClient {
	return &echoServiceWSClient{cc: cc}
}

// EchoService_ServerStreamClientWS is the typed client stream for EchoService.ServerStream.
type EchoService_ServerStreamClientWS struct {
	stream *wsrpc.Stream
}

func (x *EchoService_ServerStreamClientWS) Send(msg *ServerStreamRequest) error {
	return x.stream.Send(msg)
}

func (x *EchoService_ServerStreamClientWS) Recv() (*ServerStreamResponse, error) {
	msg := new(ServerStreamResponse)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *EchoService_ServerStreamClientWS) CloseSend() error {
	return x.stream.CloseSend()
}

// Header returns the leading response headers (KIND_HEADER), if the server sent any.
func (x *EchoService_ServerStreamClientWS) Header() map[string]string {
	return x.stream.Header()
}

// Trailer returns the response trailers carried on the END frame.
func (x *EchoService_ServerStreamClientWS) Trailer() map[string]string {
	return x.stream.Trailer()
}

// EchoService_ClientStreamClientWS is the typed client stream for EchoService.ClientStream.
type EchoService_ClientStreamClientWS struct {
	stream *wsrpc.Stream
}

func (x *EchoService_ClientStreamClientWS) Send(msg *ClientStreamRequest) error {
	return x.stream.Send(msg)
}

func (x *EchoService_ClientStreamClientWS) Recv() (*ClientStreamResponse, error) {
	msg := new(ClientStreamResponse)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *EchoService_ClientStreamClientWS) CloseSend() error {
	return x.stream.CloseSend()
}

// Header returns the leading response headers (KIND_HEADER), if the server sent any.
func (x *EchoService_ClientStreamClientWS) Header() map[string]string {
	return x.stream.Header()
}

// Trailer returns the response trailers carried on the END frame.
func (x *EchoService_ClientStreamClientWS) Trailer() map[string]string {
	return x.stream.Trailer()
}

func (x *EchoService_ClientStreamClientWS) CloseAndRecv() (*ClientStreamResponse, error) {
	if err := x.stream.CloseSend(); err != nil {
		return nil, err
	}
	return x.Recv()
}

// EchoService_BidiClientWS is the typed client stream for EchoService.Bidi.
type EchoService_BidiClientWS struct {
	stream *wsrpc.Stream
}

func (x *EchoService_BidiClientWS) Send(msg *BidiRequest) error {
	return x.stream.Send(msg)
}

func (x *EchoService_BidiClientWS) Recv() (*BidiResponse, error) {
	msg := new(BidiResponse)
	if err := x.stream.Recv(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

func (x *EchoService_BidiClientWS) CloseSend() error {
	return x.stream.CloseSend()
}

// Header returns the leading response headers (KIND_HEADER), if the server sent any.
func (x *EchoService_BidiClientWS) Header() map[string]string {
	return x.stream.Header()
}

// Trailer returns the response trailers carried on the END frame.
func (x *EchoService_BidiClientWS) Trailer() map[string]string {
	return x.stream.Trailer()
}

func (c *echoServiceWSClient) Unary(ctx context.Context, req *UnaryRequest, opts ...wsrpc.CallOption) (*UnaryResponse, error) {
	headers := wsrpc.CallHeaders(opts...)
	s, err := c.cc.NewStream(ctx, "/echo.v1.EchoService/Unary", headers)
	if err != nil {
		return nil, err
	}
	if err := s.Send(req); err != nil {
		return nil, err
	}
	if err := s.CloseSend(); err != nil {
		return nil, err
	}
	res := new(UnaryResponse)
	if err := s.Recv(res); err != nil {
		return nil, err
	}
	if err := s.Recv(new(UnaryResponse)); err != nil && err != io.EOF {
		return nil, err
	}
	return res, nil
}

func (c *echoServiceWSClient) ServerStream(ctx context.Context, req *ServerStreamRequest, opts ...wsrpc.CallOption) (*EchoService_ServerStreamClientWS, error) {
	headers := wsrpc.CallHeaders(opts...)
	s, err := c.cc.NewStream(ctx, "/echo.v1.EchoService/ServerStream", headers)
	if err != nil {
		return nil, err
	}
	if err := s.Send(req); err != nil {
		return nil, err
	}
	if err := s.CloseSend(); err != nil {
		return nil, err
	}
	return &EchoService_ServerStreamClientWS{stream: s}, nil
}

func (c *echoServiceWSClient) ClientStream(ctx context.Context, opts ...wsrpc.CallOption) (*EchoService_ClientStreamClientWS, error) {
	headers := wsrpc.CallHeaders(opts...)
	s, err := c.cc.NewStream(ctx, "/echo.v1.EchoService/ClientStream", headers)
	if err != nil {
		return nil, err
	}
	return &EchoService_ClientStreamClientWS{stream: s}, nil
}

func (c *echoServiceWSClient) Bidi(ctx context.Context, opts ...wsrpc.CallOption) (*EchoService_BidiClientWS, error) {
	headers := wsrpc.CallHeaders(opts...)
	s, err := c.cc.NewStream(ctx, "/echo.v1.EchoService/Bidi", headers)
	if err != nil {
		return nil, err
	}
	return &EchoService_BidiClientWS{stream: s}, nil
}

// echoServiceGRPCBridge adapts a gRPC EchoServiceServer to a EchoServiceHandler.
type echoServiceGRPCBridge struct {
	impl EchoServiceServer
	cfg  wsrpc.BridgeConfig
}

// EchoServiceFromGRPC wraps a protoc-gen-go-grpc server so it can be
// registered on a wsrpc.Server via RegisterEchoServiceHandler. Optional
// wsrpc.BridgeOption values install gRPC server interceptors run around RPCs.
func EchoServiceFromGRPC(impl EchoServiceServer, opts ...wsrpc.BridgeOption) EchoServiceHandler {
	return &echoServiceGRPCBridge{impl: impl, cfg: wsrpc.ApplyBridgeOptions(opts...)}
}

// echoServiceGRPCStream adapts *wsrpc.Stream to grpc.ServerStream. When capturing is set
// (client-streaming), SendMsg captures the response instead of sending it, so
// the bridge can return it through the wsrpc handler contract.
type echoServiceGRPCStream struct {
	stream        *wsrpc.Stream
	ctx           context.Context
	capturing     bool
	captured      proto.Message
	pendingHeader metadata.MD // buffered leading headers, flushed on SendHeader or first SendMsg
}

func (x *echoServiceGRPCStream) Context() context.Context { return x.ctx }

// SetHeader buffers leading header metadata; it is sent on the first
// SendMsg or an explicit SendHeader (gRPC ServerStream semantics).
func (x *echoServiceGRPCStream) SetHeader(md metadata.MD) error {
	if x.pendingHeader == nil {
		x.pendingHeader = metadata.MD{}
	}
	for k, v := range md {
		x.pendingHeader[k] = append(x.pendingHeader[k], v...)
	}
	return nil
}

// SendHeader merges md into the pending headers and flushes them as a
// leading KIND_HEADER frame on the underlying wsrpc stream.
func (x *echoServiceGRPCStream) SendHeader(md metadata.MD) error {
	if err := x.SetHeader(md); err != nil {
		return err
	}
	err := x.stream.SendHeader(wsrpc.FlattenMD(x.pendingHeader))
	x.pendingHeader = nil
	return err
}

// SetTrailer merges md into the trailers flushed with the END frame.
func (x *echoServiceGRPCStream) SetTrailer(md metadata.MD) {
	x.stream.SetTrailer(wsrpc.FlattenMD(md))
}

func (x *echoServiceGRPCStream) SendMsg(m any) error {
	pm, ok := m.(proto.Message)
	if !ok {
		return wsrpc.Errorf(codes.Internal, "wsrpc: SendMsg expected proto.Message")
	}
	if x.capturing {
		x.captured = pm
		return nil
	}
	// Flush any buffered leading headers before the first response message
	// (best-effort: ignore FailedPrecondition if headers were already sent).
	if x.pendingHeader != nil {
		_ = x.stream.SendHeader(wsrpc.FlattenMD(x.pendingHeader))
		x.pendingHeader = nil
	}
	return x.stream.Send(pm)
}

func (x *echoServiceGRPCStream) RecvMsg(m any) error {
	pm, ok := m.(proto.Message)
	if !ok {
		return wsrpc.Errorf(codes.Internal, "wsrpc: RecvMsg expected proto.Message")
	}
	return x.stream.Recv(pm)
}

func (b *echoServiceGRPCBridge) Unary(ctx context.Context, req *UnaryRequest) (*UnaryResponse, error) {
	if b.cfg.Unary == nil {
		return b.impl.Unary(ctx, req)
	}
	info := &grpc.UnaryServerInfo{Server: b.impl, FullMethod: "/echo.v1.EchoService/Unary"}
	resp, err := b.cfg.Unary(ctx, req, info, func(ctx context.Context, r any) (any, error) {
		return b.impl.Unary(ctx, r.(*UnaryRequest))
	})
	if err != nil {
		return nil, err
	}
	out, ok := resp.(*UnaryResponse)
	if !ok {
		return nil, wsrpc.Errorf(codes.Internal, "wsrpc: EchoService.Unary interceptor returned unexpected response type")
	}
	return out, nil
}

func (b *echoServiceGRPCBridge) ServerStream(ctx context.Context, req *ServerStreamRequest, stream *EchoService_ServerStreamServerWS) error {
	base := &echoServiceGRPCStream{stream: stream.stream, ctx: ctx}
	h := func(_ any, ss grpc.ServerStream) error {
		return b.impl.ServerStream(req, &grpc.GenericServerStream[ServerStreamRequest, ServerStreamResponse]{ServerStream: ss})
	}
	if b.cfg.Stream == nil {
		return h(b.impl, base)
	}
	info := &grpc.StreamServerInfo{FullMethod: "/echo.v1.EchoService/ServerStream", IsServerStream: true}
	return b.cfg.Stream(b.impl, base, info, h)
}

func (b *echoServiceGRPCBridge) ClientStream(ctx context.Context, stream *EchoService_ClientStreamServerWS) (*ClientStreamResponse, error) {
	base := &echoServiceGRPCStream{stream: stream.stream, ctx: ctx, capturing: true}
	h := func(_ any, ss grpc.ServerStream) error {
		return b.impl.ClientStream(&grpc.GenericServerStream[ClientStreamRequest, ClientStreamResponse]{ServerStream: ss})
	}
	var err error
	if b.cfg.Stream == nil {
		err = h(b.impl, base)
	} else {
		info := &grpc.StreamServerInfo{FullMethod: "/echo.v1.EchoService/ClientStream", IsClientStream: true}
		err = b.cfg.Stream(b.impl, base, info, h)
	}
	if err != nil {
		return nil, err
	}
	if base.captured == nil {
		return nil, wsrpc.Errorf(codes.Internal, "wsrpc: EchoService.ClientStream handler returned without SendAndClose")
	}
	return base.captured.(*ClientStreamResponse), nil
}

func (b *echoServiceGRPCBridge) Bidi(ctx context.Context, stream *EchoService_BidiServerWS) error {
	base := &echoServiceGRPCStream{stream: stream.stream, ctx: ctx}
	h := func(_ any, ss grpc.ServerStream) error {
		return b.impl.Bidi(&grpc.GenericServerStream[BidiRequest, BidiResponse]{ServerStream: ss})
	}
	if b.cfg.Stream == nil {
		return h(b.impl, base)
	}
	info := &grpc.StreamServerInfo{FullMethod: "/echo.v1.EchoService/Bidi", IsClientStream: true, IsServerStream: true}
	return b.cfg.Stream(b.impl, base, info, h)
}
