// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/echo/v1/echo.proto

package echov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryRequest) Reset() {
	*x = UnaryRequest{}
	mi := &file_proto_echo_v1_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryRequest) ProtoMessage() {}

func (x *UnaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_v1_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryRequest.ProtoReflect.Descriptor instead.
func (*UnaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_v1_echo_proto_rawDescGZIP(), []int{0}
}

func (x *UnaryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UnaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryResponse) Reset() {
	*x = UnaryResponse{}
	mi := &file_proto_echo_v1_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryResponse) ProtoMessage() {}

func (x *UnaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_v1_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryResponse.ProtoReflect.Descriptor instead.
func (*UnaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_v1_echo_proto_rawDescGZIP(), []int{1}
}

func (x *UnaryResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type ServerStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStreamRequest) Reset() {
	*x = ServerStreamRequest{}
	mi := &file_proto_echo_v1_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamRequest) ProtoMessage() {}

func (x *ServerStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_v1_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamRequest.ProtoReflect.Descriptor instead.
func (*ServerStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_v1_echo_proto_rawDescGZIP(), []int{2}
}

func (x *ServerStreamRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ServerStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStreamResponse) Reset() {
	*x = ServerStreamResponse{}
	mi := &file_proto_echo_v1_echo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamResponse) ProtoMessage() {}

func (x *ServerStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_v1_echo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamResponse.ProtoReflect.Descriptor instead.
func (*ServerStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_v1_echo_proto_rawDescGZIP(), []int{3}
}

func (x *ServerStreamResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ClientStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStreamRequest) Reset() {
	*x = ClientStreamRequest{}
	mi := &file_proto_echo_v1_echo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamRequest) ProtoMessage() {}

func (x *ClientStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_v1_echo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamRequest.ProtoReflect.Descriptor instead.
func (*ClientStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_v1_echo_proto_rawDescGZIP(), []int{4}
}

func (x *ClientStreamRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ClientStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sum           int32                  `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStreamResponse) Reset() {
	*x = ClientStreamResponse{}
	mi := &file_proto_echo_v1_echo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamResponse) ProtoMessage() {}

func (x *ClientStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_v1_echo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamResponse.ProtoReflect.Descriptor instead.
func (*ClientStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_v1_echo_proto_rawDescGZIP(), []int{5}
}

func (x *ClientStreamResponse) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type BidiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidiRequest) Reset() {
	*x = BidiRequest{}
	mi := &file_proto_echo_v1_echo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiRequest) ProtoMessage() {}

func (x *BidiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_v1_echo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiRequest.ProtoReflect.Descriptor instead.
func (*BidiRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_v1_echo_proto_rawDescGZIP(), []int{6}
}

func (x *BidiRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type BidiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Echo          string                 `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidiResponse) Reset() {
	*x = BidiResponse{}
	mi := &file_proto_echo_v1_echo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiResponse) ProtoMessage() {}

func (x *BidiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_v1_echo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiResponse.ProtoReflect.Descriptor instead.
func (*BidiResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_v1_echo_proto_rawDescGZIP(), []int{7}
}

func (x *BidiResponse) GetEcho() string {
	if x != nil {
		return x.Echo
	}
	return ""
}

var File_proto_echo_v1_echo_proto protoreflect.FileDescriptor

const file_proto_echo_v1_echo_proto_rawDesc = "" +
	"\n" +
	"\x18proto/echo/v1/echo.proto\x12\aecho.v1\"\"\n" +
	"\fUnaryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\rUnaryResponse\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting\"+\n" +
	"\x13ServerStreamRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\",\n" +
	"\x14ServerStreamResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\"+\n" +
	"\x13ClientStreamRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\"(\n" +
	"\x14ClientStreamResponse\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x05R\x03sum\"!\n" +
	"\vBidiRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\"\n" +
	"\fBidiResponse\x12\x12\n" +
	"\x04echo\x18\x01 \x01(\tR\x04echo2\x9c\x02\n" +
	"\vEchoService\x126\n" +
	"\x05Unary\x12\x15.echo.v1.UnaryRequest\x1a\x16.echo.v1.UnaryResponse\x12M\n" +
	"\fServerStream\x12\x1c.echo.v1.ServerStreamRequest\x1a\x1d.echo.v1.ServerStreamResponse0\x01\x12M\n" +
	"\fClientStream\x12\x1c.echo.v1.ClientStreamRequest\x1a\x1d.echo.v1.ClientStreamResponse(\x01\x127\n" +
	"\x04Bidi\x12\x14.echo.v1.BidiRequest\x1a\x15.echo.v1.BidiResponse(\x010\x01B;Z9github.com/gopherex/ws-proto/example/proto/echo/v1;echov1b\x06proto3"

var (
	file_proto_echo_v1_echo_proto_rawDescOnce sync.Once
	file_proto_echo_v1_echo_proto_rawDescData []byte
)

func file_proto_echo_v1_echo_proto_rawDescGZIP() []byte {
	file_proto_echo_v1_echo_proto_rawDescOnce.Do(func() {
		file_proto_echo_v1_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_echo_v1_echo_proto_rawDesc), len(file_proto_echo_v1_echo_proto_rawDesc)))
	})
	return file_proto_echo_v1_echo_proto_rawDescData
}

var file_proto_echo_v1_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_echo_v1_echo_proto_goTypes = []any{
	(*UnaryRequest)(nil),         // 0: echo.v1.UnaryRequest
	(*UnaryResponse)(nil),        // 1: echo.v1.UnaryResponse
	(*ServerStreamRequest)(nil),  // 2: echo.v1.ServerStreamRequest
	(*ServerStreamResponse)(nil), // 3: echo.v1.ServerStreamResponse
	(*ClientStreamRequest)(nil),  // 4: echo.v1.ClientStreamRequest
	(*ClientStreamResponse)(nil), // 5: echo.v1.ClientStreamResponse
	(*BidiRequest)(nil),          // 6: echo.v1.BidiRequest
	(*BidiResponse)(nil),         // 7: echo.v1.BidiResponse
}
var file_proto_echo_v1_echo_proto_depIdxs = []int32{
	0, // 0: echo.v1.EchoService.Unary:input_type -> echo.v1.UnaryRequest
	2, // 1: echo.v1.EchoService.ServerStream:input_type -> echo.v1.ServerStreamRequest
	4, // 2: echo.v1.EchoService.ClientStream:input_type -> echo.v1.ClientStreamRequest
	6, // 3: echo.v1.EchoService.Bidi:input_type -> echo.v1.BidiRequest
	1, // 4: echo.v1.EchoService.Unary:output_type -> echo.v1.UnaryResponse
	3, // 5: echo.v1.EchoService.ServerStream:output_type -> echo.v1.ServerStreamResponse
	5, // 6: echo.v1.EchoService.ClientStream:output_type -> echo.v1.ClientStreamResponse
	7, // 7: echo.v1.EchoService.Bidi:output_type -> echo.v1.BidiResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_echo_v1_echo_proto_init() }
func file_proto_echo_v1_echo_proto_init() {
	if File_proto_echo_v1_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_echo_v1_echo_proto_rawDesc), len(file_proto_echo_v1_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_echo_v1_echo_proto_goTypes,
		DependencyIndexes: file_proto_echo_v1_echo_proto_depIdxs,
		MessageInfos:      file_proto_echo_v1_echo_proto_msgTypes,
	}.Build()
	File_proto_echo_v1_echo_proto = out.File
	file_proto_echo_v1_echo_proto_goTypes = nil
	file_proto_echo_v1_echo_proto_depIdxs = nil
}
